%Load the image labelled data
load ('deep_gt_automated.mat');

%Generate training data    
trainingData = objectDetectorTrainingData(gTruth);

%Set training options
    options = trainingOptions('sgdm', ...
        'MiniBatchSize', 128, ...
        'InitialLearnRate', 1e-3, ...
        'LearnRateSchedule', 'piecewise', ...
        'LearnRateDropFactor', 0.1, ...
        'LearnRateDropPeriod', 100, ...
        'MaxEpochs', 100, ...
        'Verbose', true, ...
        'ExecutionEnvironment','gpu');
 % pretrained data   
load('rcnnStopSigns.mat','cifar10Net');
%Train an R-CNN object detector using pretrained dataset    
rcnn = trainRCNNObjectDetector(trainingData, cifar10Net, options, ...
'NegativeOverlapRange', [0 0.3], 'PositiveOverlapRange',[0.5 1]) 